name: Zip Resourcepack

on: [push]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Archive resourcepack
        uses: actions/upload-artifact@v4
        with:
          name: flowsmp
          path: |
            README.md
            pack.png
            pack.mcmeta
            assets/
            data/
